// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace JumpToFileAtCursorVisualStudioExtension;

internal sealed partial class Vsix
{
    public const string Id = "JumpToFileAtCursorVisualStudioExtension.5566d557-8ab9-4432-872b-7125df7bf5c1";
    public const string Name = "JumpToFileAtCursorVisualStudioExtension";
    public const string Description = @"Empty VSIX Project.";
    public const string Language = "en-US";
    public const string Version = "1.0";
    public const string Author = "Martin Andersen";
    public const string Tags = "";
}
