// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace JumpToFileAtCursorVisualStudioExtension
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string JumpToFileAtCursorVisualStudioExtensionString = "fd8f8e98-70d5-43f3-a2f9-b1ab9b4b36a9";
        public static Guid JumpToFileAtCursorVisualStudioExtension = new Guid(JumpToFileAtCursorVisualStudioExtensionString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int JumpToFileCommand = 0x0001;
    }
}
