// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the free extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace JumpToFileAtCursorVisualStudioExtension;

using System;

/// <summary>
/// Helper class that exposes all GUIDs used across VS Package.
/// </summary>
internal sealed partial class PackageGuids
{
    public const string JumpToFileAtCursorVisualStudioExtensionString = "fd8f8e98-70d5-43f3-a2f9-b1ab9b4b36a9";
    public static Guid JumpToFileAtCursorVisualStudioExtension = new Guid(JumpToFileAtCursorVisualStudioExtensionString);
}
/// <summary>
/// Helper class that encapsulates all CommandIDs uses across VS Package.
/// </summary>
internal sealed partial class PackageIds
{
}